import math

HEIGHT = 720
WIDTH = 1080
BALL_X, BALL_Y = WIDTH / 2, HEIGHT / 2
BALL_VX, BALL_VY, BALL_SIZE = HEIGHT / 120, HEIGHT / 120, HEIGHT / 60
PADDLE_WIDTH, PADDLE_HEIGHT = WIDTH / 16, HEIGHT / 60
PADDLE_X, PADDLE_Y = (WIDTH - PADDLE_HEIGHT) / 2, (HEIGHT - (HEIGHT / 25))
PADDLE_SPEED = HEIGHT * 1.5 / 100
MAX_ANGLE = math.radians(60)
LEFT = ["a", "Left"]
RIGHT = ["d", "Right"]
SPACE = ["space"]
ALL_KEYS = LEFT + RIGHT + SPACE
